# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2020 Bombardier Transportation
# Ulf Samuelsson <ulf@emagii.com>
#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-y	:= mux.o
obj-y	+= gpmc.o
obj-y	+= board.o

obj-$(CONFIG_LED_STATUS) += led.o
